pipeline{
    agent any
    environment{
        replicas = 10
        DATABASE_URI = credentials("DATABASE_URI")
        app_version = 'v2'
        rollback = 'false'
     
    }
    stages{
        stage("Testing"){
            steps{
                sh "bash jenkins/test.sh"
            }
        }
        stage("Push image"){
            environment{
                docker_credentials = credentials('docker-hub-credentials')
            }
            steps{
                sh "bash jenkins/docker_build.sh"
                sh "docker system prune -af"
            }
        }
    
        
        
        stage("Configure Swarm and ansible"){
        steps{
            sh "cd ansible && /home/jenkins/.local/bin/ansible-playbook -i inventory playbook.yaml"
            }
        }
        stage("Deploy application"){
        steps{
            sh "bash jenkins/deploy_stack.sh"
            }
        }
    }
    post{
        always{
            junit "**/junit.xml"
            cobertura coberturaReportFile: '**/coverage.xml'
        }
    }
}
