pipeline{
    agent any
    environment{
        TEST_DATABASE_URI = "sqlite://data.db"
        TEST_SECRET_KEY = "test"
        DB_PASSWORD = credentials("DB_PASSWORD")
    }
    stages{
        stage('Build App and Push Images'){
            steps{
                sh "bash jenkins/docker_build.sh"
            }
        }
    }
    stage("Configure Swarm and ansible"){
        steps{
            sh "cd ansible && /home/jenkins/.local/bin/ansible-playbook -i inventory playbook.yaml"
        }
    }
    stage("Deploy application"){
        steps{
            sh "bash jenkins/deploy_stack.sh"
        }
}