pipeline{
    agent any
    environment{
        DATABASE_URI = credentials("DATABASE_URI")
    }
    stages{
        stage("Configure Swarm and ansible"){
        steps{
            sh "cd ansible && /home/jenkins/.local/bin/ansible-playbook -i inventory playbook.yaml"
        }
    }
    stage("Deploy application"){
        steps{
            sh "bash jenkins/deploy_stack.sh"
        }
    }
    }
}
