---
	- name: add jenkins user
	  user:
	  	name: jenkins
		groups: docker
		shell: /bin/bash
		append: true

	- name: Initialise a new swarm
	  community.general.docker_swarm:
		state: present
	  register: swarm_info
