---
- name: set-up nginx
  become: true
  hosts: nginx
  roles:
    - nginx
- name: initialize docker swarm
  become: true
  hosts: managers
  roles:
    - docker
    - swarm-init
- name: add workers to swarm
  become: true
  hosts: workers
  roles:
    - docker
    - swarm-worker